name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*" # Use the latest LTS version
      - uses: pnpm/action-setup@v4
        with:
          version: 8.6.0
          run_install: true
      - name: Lint
        run: pnpm -F graph-selector lint:ci
      - name: Run Tests
        run: pnpm test
