name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*" # Use the latest LTS version
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 8.6.0
          run_install: true
      - name: Lint
        run: pnpm -F graph-selector lint:ci
      - name: Run Tests
        run: pnpm test
      # - name: Upload Coverage
      #   uses: codecov/codecov-action@v3
      #   with:
      #     root_dir: ./graph-selector # optional (default = .)
      #     fail_ci_if_error: false # optional (default = false)
      #     verbose: true # optional (default = false)
      #     token: ${{ secrets.CODECOV_TOKEN }} # optional
