name: Test
on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7.11.0
      - name: Install Dependencies
        run: pnpm install
      - name: Lint
        run: pnpm -F graph-selector lint:ci
      - name: Run Tests
        run: pnpm test:coverage
      - name: Upload Coverage
        uses: codecov/codecov-action@v2
        with:
          root_dir: ./parser
          fail_ci_if_error: false # optional (default = false)
          verbose: true # optional (default = false)
